# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
fastlane_version "2.68.0"
default_platform :android


platform :android do
    desc "Submit a new Beta Build to Firebase app distribution"
    lane :beta do
        # build the release variant
        build_android_app(task: "assembleRelease")

        # changelog from a txt file is passed as the release note
      # changelog = File.read("../changelog.txt")

        # submit build to firebase app distribution
        firebase_app_distribution(
            app: "1:571486779932:android:3034fece0ec81396cdbdd9",
            testers: "giovincentromero7@gmail.com",
            release_notes: "Test"


        )

        # send slack success notification after distribution completes

    end

    # handle exception
    error do |lane, exception, options|
        # send slack failure notification

    end
end